# Generated by Django 4.0.6 on 2022-09-08 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kuthibitisha', '0002_alter_profile_user_alter_profile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=True, max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
